services:
  notifications:
    deploy:
      replicas: ${NOTIFICATIONS_SERVICE_REPLICAS:-1}
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
    depends_on: []

networks:
  eventonight-network:
    driver: overlay
  notifications-network:
    driver: overlay
