services:
    keycloak:
      build:
        context: .
        dockerfile: ./infrastructure/authentication/Dockerfile-keycloak

    keycloak-provision:
      build:
        context: .
        dockerfile: ./infrastructure/authentication/Dockerfile-keycloak-provision    