services:
  postgres-keycloak:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      timeout: 5s

  keycloak:
    image: ghcr.io/eventonight/eventonight/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_LOGLEVEL: INFO
      KC_METRICS_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    networks:
      - eventonight-network
      - keycloak-network
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/8080' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 600s

  keycloak-provision:
    image: ghcr.io/eventonight/eventonight/keycloak-provision:latest
    container_name: keycloak-provision
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      USERS_SERVICE_SECRET: ${USERS_SERVICE_SECRET}
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - keycloak-network

volumes:
  keycloak-postgres-data:

networks:
  eventonight-network:
    driver: bridge
  keycloak-network:
    driver: bridge
