services:
  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
      args:
        HOST: ${HOST}
    ports:
      - "${FRONTEND_SERVICE_PORT}:${FRONTEND_SERVICE_PORT}"