services:
  frontend:
    image: ghcr.io/eventonight/eventonight/frontend:latest
    networks:
      - eventonight-network  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HOST}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=${FRONTEND_SERVICE_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
    restart: unless-stopped
    deploy:
      replicas: ${FRONTEND_SERVICE_REPLICAS:-1}
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
    environment:
        - VITE_HOST=${HOST}
        - PORT=${FRONTEND_SERVICE_PORT}

networks:
  eventonight-network:
    driver: bridge