services:
  frontend:
    image: ghcr.io/eventonight/eventonight/frontend:latest
    networks:
      - eventonight-network  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HOST}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=${FRONTEND_SERVICE_PORT}"
    restart: unless-stopped

networks:
  eventonight-network:
    driver: bridge