services:
  interactions:
    image: ghcr.io/eventonight/eventonight/interactions:latest
    networks:
      - eventonight-network
      - interactions-network
    environment:
      - PORT=${INTERACTIONS_SERVICE_PORT}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - MONGO_HOST=mongo-interactions
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactions.rule=Host(`interactions.${HOST}`)"
      - "traefik.http.routers.interactions.entrypoints=web"
      - "traefik.http.services.interactions.loadbalancer.server.port=${INTERACTIONS_SERVICE_PORT}"
    restart: unless-stopped
    depends_on:
      mongo-interactions:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mongo-interactions:
    image: mongo
    restart: unless-stopped
    networks:
      - interactions-network
    healthcheck:
      test: [ 'CMD', 'mongosh', '--quiet', '--eval', 'db.runCommand({ ping: 1 }).ok' ]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 30s

networks:
  eventonight-network:
    driver: bridge
  interactions-network:
    driver: bridge