services:
  media:
    image: ghcr.io/eventonight/eventonight/media:latest
    networks:
      - eventonight-network
      - media-network
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=eventonightadmin
      - MINIO_SECRET_KEY=${MINIO_PASSWORD:?}
      - MINIO_BUCKET=eventonight-media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`media.${HOST}`)"
      - "traefik.http.routers.media.entrypoints=web"
      - "traefik.http.services.media.loadbalancer.server.port=9020"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9020/health"]
      interval: 2s
      timeout: 3s
      retries: 100
      start_period: 500s
    depends_on:
      - minio

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9021:9000"
    environment:
      - MINIO_ROOT_USER=eventonightadmin
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD:?}
    volumes:
      - minio-data:/data
    networks:
      - media-network

volumes:
  minio-data:

networks:
  eventonight-network:
    driver: bridge
  media-network:
    driver: bridge
