services:
  media:
    image: ghcr.io/eventonight/eventonight/media:latest
    networks:
      - eventonight-network
      - media-network
    environment:
      - PORT=9020
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
      - MINIO_BUCKET=event-images
      - MINIO_PUBLIC_URL=http://minio:9021
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`media.${HOST}`)"
      - "traefik.http.routers.media.entrypoints=web"
      - "traefik.http.services.media.loadbalancer.server.port=9020"
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    ports:
      - "9021:9000"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio-data:/data
    networks:
      - media-network

volumes:
  minio-data:

networks:
  eventonight-network:
    driver: bridge
  media-network:
    driver: bridge  
