services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    networks:
      - dev-network
    ports:
      - '5672:5672'
    healthcheck:
      test: [ 'CMD', 'rabbitmqctl', 'await_startup' ]
      interval: 5s
      timeout: 120s
      retries: 1000
      start_period: 500s

  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - dev-network
    ports:
      - '27017:27017'
    healthcheck:
      test: [ 'CMD', 'mongosh', '--quiet', '--eval', 'db.runCommand({ ping: 1 }).ok' ]
      interval: 2s
      timeout: 3s
      retries: 1000
      start_period: 500s

networks:
  dev-network:
    driver: bridge